### ISSUE TITLE
Define core schema

### ISSUE THREAD

**Issue by andru** [openfarmcc/Crops#5]
A space to discuss a core schema.  Entries could contain additional data, but it would be useful to define a schema that all entries share.

@pmackay and @mstenta already got started at this over at https://github.com/openfarmcc/Crops/wiki/Crop-data-needs, but I'm opening this for some parallel discussion which we can port over to the wiki as we reach consensus.

**Comment by andru** [comment]
Here's my take on a minimal schema, divided by category.

## Entity Identification

### A unique identifier

Probably something arbitrary or an established scientific name. In the latter case, we'd have to choose which nomenclature.

## Taxonomy and nomenclature

This section defines the crop being described for interoperability with other data sets

### Taxonomy

#### Taxonomic hierarchy

An array of the taxonomic hierarchy, starting at the family level.  e.g. 

```
[Solanaceae, Lycopersicon, esculentum]
[Brassicaceae, Brassica, oleracea, italica]
```

### Names

#### Scientific nomenclature

The names assigned to this plant by different nomenclatures. Relevent to a crop database these are [ICN](https://en.wikipedia.org/wiki/International_Code_of_Nomenclature_for_algae,_fungi,_and_plants) and [ICNCP](https://en.wikipedia.org/wiki/International_Code_of_Nomenclature_for_Cultivated_Plants).  There will often be a name for common plants in each nomenclature, and there will be synonyms. Keeping a list of all synonyms is out of scope, but we should list the common ones which some people continue to use.
e.g. Broccoli

```
{
  accepted: [
    ['Brassica oleracea var italica', 'ICN']
    [Brassica oleracea Italica Group', 'ICNCP']
  ],
  synonyms: [ ] 
}
```

#### Common names

By language or locale

```
{
  en: ['Broccoli', 'Heading Cauliflower', 'Calabrese', 'Purple Cauliflower']
  en_GB: ['Spear Cauliflower']
  es: ['Brecol']
  pt: ['Brócolis']
}
```

## Phenology

This section is going to be tricky to define a core schema for, because crops all have different triggers for various life cycle stages.

I'm more or less ok with the idea of a simple 'days to maturity' or 'days to germination' field as a shortcut to this data as long as we understand that such figures totally relative to the environment and the common numbers you'll find in English growing literature are usually for temperate climates and are totally inaccurate elsewhere.  
At the least we should have the means to define those figures relative to different climates somehow. Ideally, though, I think it would be better to have a schema which represents the underlying phenology data which influences the number of days to a certain life stage.

### Germination
- Low/High temperature boundaries
- Cumulative temperature (cold or heat)
- Moisture

### Fruiting and Flowering triggers
- number of days
- day length boundary (short day/long day preference)
- cumulative temperature ([GDD](https://en.wikipedia.org/wiki/Growing_degree-day))
- temperature boundary
- soil moisture 

### Other phenological properties we might want to consider
- leaf stages (industrial farming uses this as a predictive model for harvest timing)
- dormancy
- seed ripening
- ...

## Environmental tolerance
- genetic drought tolerance
- minimum _survival_ temperature
- PH tolerance to thrive

## Technique / unscientific data

I think `crop spacing`, `yield` and `method of planting` should be out of scope for this database. All three are strongly relative to personal preference and environmental conditions. 

Ok, that's what I've got for now...

**Comment by andru** [comment]
Here's a rough example of a crop using something like the above schema

```
id: aTHneohsT£@23th
inherits: id-for-brassica-oleracea-entry
taxonomicHierarchy: [Brassicaceae, Brassica, oleracea, italica]
names: 
   - [Brassica oleracea var italica, ICN]
   - [Brassica oleracea Italica Group, ICNCP]
synonyms: [ ]
commonNames: 
  en: [Broccoli, Heading Cauliflower, Calabrese, Purple Cauliflower]
  en_GB: [Spear Cauliflower]
  es: [Brecol]
  pt: [Brócolis]
averageDaysTo: 
  harvest: [25, 90]
  flowering: [100, 110]
phenology:
  germination:
    - [45, Growing Degree Days Until Germination]
    - [20, Days Cold Stratification Required] 
  flowering:
    - [16, Ideal Maximum Temperature ºC]
    - [13, Minimum Hours Day Length]
environmentalTolerances:
   - [-12, Minimum Temperature]
```

Here's an example of why days-to type data is tricky... The data I was using for some of this entry is this: 

> May be harvested after 40-60 or 50-90 days, depending on variety. (Eswaran) 25-45 days for leaves and 100-110 days for seeds

So, harvest time for the whole plant is 40-60, or 50-90, or for just an outer leaf harvest it's 25-45. That means the full range for a single property is 25-90. Ouch! We could have that overridden to a more specific value in the cultivar entries, assuming we could get that data, and we could add an additional property like

```
averageDaysTo: 
  totalHarvest: [40, 60]
  partialHarvest: [25, 45]
  flowering: [100, 110]
```

Not sure how best to model it, and in large part it depends on what data we can get our hands on.
